[package]
name = "wrote_color"
version = "0.1.0"
authors = ["iqpizza6349 <iqpizza6349@gmail.com>"]
edition = "2021"

[dependencies]
futures = { version = "0.3.28" } 
tokio = { version = "1.28.2", features = ["full"] }
websocket = "0.26.5"
